config/routes.rb
Bicicletada::Application.routes.draw do

  # login
  devise_for :admins

  # /admin
  namespace :admin do
    root :to => 'dashboard#index'
    resources :subscriptions, :only => [:index, :show]
    resources :admins
    resources :orientations
  end

  scope "(:locale)", :locale => /pt-BR|en/ do
    root :to => 'home#index'
    resources :users
    resource :bicicletada_nacional_rio_20, :as => :about, :controller => :about, :only => [:show]
    resource :rotas_bicicletada_nacional, :as => :routes, :controller => :routes, :only => [:show]
    resource :organizadores, :as => :organizers, :controller => :organizers, :only => [:show]
    resource :apoio, :as => :support, :controller => :support, :only => [:show]
    resource :contato, :as => :contact, :controller => :contact, :only => [:show]
    resources :orientacoes, :as => :orientations, :controller => :orientations, :only => [:index]
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  validates :name, :state, :presence => true
  validates :superuser, :inclusion => [true, false]

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :registerable
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :state, :superuser

  has_many :orientations
end

app/models/orientation.rb
class Orientation < ActiveRecord::Base
  belongs_to :admin
end

app/models/subscription.rb
#encoding: utf-8
class Subscription < ActiveRecord::Base

  validates :accept, :inclusion => { :in => [true], :message => "blabla" } 

  attr_accessible :name, :birth_day, :birth_place, :address, :district, :city,
                  :state, :contact_phone, :blood_type, :allergy, :emergency_name,
                  :emergency_address, :emergency_contact_phone, :rio20, :cupula_dos_povos,
                  :accept

  def rio20_humanize
    rio20? ? "Sim" : "Não"
  end

  def cupula_dos_povos_humanize
    cupula_dos_povos? ? "Sim" : "Não"
  end

  #Relationships
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :subscription_attributes

  #Validations
  validates :email, :presence => true, :uniqueness => true

  #Relationships
  has_one :subscription
  accepts_nested_attributes_for :subscription, :allow_destroy => true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/admin/admins_controller.rb
# encoding: utf-8

class Admin::AdminsController < ApplicationController

  layout 'admin'

  before_filter :admin_superuser
  before_filter :authenticate_admin!
  before_filter :admin, :only => [:edit, :update, :destroy]

  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params[:admin])

    if @admin.save
      redirect_to(admin_admins_url, :notice => 'Usuário cadastrado com sucesso!')
    else
      render :action => "new"
    end
  end

  def edit
  end

  def update
    if @admin.update_attributes(params[:admin])
      redirect_to(admin_admins_url, :notice => 'Usuário atualizado com sucesso!')
    else
      render :action => "edit"
    end
  end

  def destroy
    @admin.destroy
    redirect_to(admin_admins_url, :notice => 'Usuário excluído com sucesso!')
  end

  private

  def admin
    @admin = Admin.find(params[:id])
  end

  def admin_superuser
    if !current_admin.superuser? && (params[:id] != current_admin.id.to_s)
      redirect_to(admin_root_path, :notice => "Você não tem permissão para acessar esta página.")
    end
  end
end

app/controllers/admin/dashboard_controller.rb
# encoding: utf-8

class Admin::DashboardController < ApplicationController

  layout 'admin'

  before_filter :authenticate_admin!

  def index
  end

end

app/controllers/admin/orientations_controller.rb
#encoding: utf-8
class Admin::OrientationsController < ApplicationController

  before_filter :orientation, :only => [:admin_superuser, :destroy, :edit, :show, :update]
  before_filter :admin_superuser, :only => [:edit, :show] 
  before_filter :authenticate_admin!

  layout "admin"

  def index
    if current_admin.superuser?
      @orientations = Orientation.order("created_at DESC")
    else
      @orientations = current_admin.orientations.order("created_at DESC")
    end
  end

  def show
  end

  def new
    @orientation = Orientation.new
  end

  def edit
  end

  def create
    @orientation = Orientation.new(params[:orientation])
    @orientation.admin = current_admin

    if @orientation.save
      redirect_to admin_orientations_path, notice: 'Orientação criada com sucesso!' 
    else
      render action: "new" 
    end
  end

  def update
    if @orientation.update_attributes(params[:orientation])
      redirect_to admin_orientations_path, notice: 'Orientação atualizada com sucesso!' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @orientation.destroy

    redirect_to admin_orientations_path
  end

  private

  def orientation
    @orientation = Orientation.find(params[:id])
  end

  def admin_superuser
    if !current_admin.superuser? && (@orientation.admin.id != current_admin.id)
      redirect_to(admin_root_path, :notice => "Você não tem permissão para acessar esta página.")
    end
  end
end

app/controllers/admin/subscriptions_controller.rb
#encoding: utf-8

class Admin::SubscriptionsController < ApplicationController

  before_filter :admin_superuser
  before_filter :authenticate_admin!
  
  layout "admin"

  def index
    @subscriptions = Subscription.all
  end

  def show
    @subscription = Subscription.find(params[:id])
  end

  private

  def admin_superuser
    if !current_admin.superuser?
      redirect_to(admin_root_path, :notice => "Você não tem permissão para acessar esta página.")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :set_locale
  layout :layout_by_resource

  protect_from_forgery

  def subscriptions_counting
    @subscriptions_counting = Subscription.count
    @orientations = Orientation.joins(:admin).where("admins.superuser = 1").order("orientations.created_at DESC")
  end

  private

  def set_locale
    I18n.locale = params[:locale] if params.include?('locale')
  end

  def default_url_options(options={})
    options.merge!({ :locale => I18n.locale })
  end

  protected

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "admin"
    else
      "application"
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/orientations_controller.rb
class OrientationsController < ApplicationController 
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
  before_filter :subscriptions_counting

  def new
    @user = User.new
    @user.build_subscription if @user.subscription.blank?
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to(root_path, :notice => "Ficha de inscrição cadastrada com sucesso!")
    else
      flash[:error] = "NÃO FOI POSSÍVEL COMPLETAR SEU CADASTRO, FAVOR VERIFICAR SE OS DADOS ESTÃO PREENCHIDOS CORRETAMENTE."
      render :action => "new"
    end
  end

end

app/helpers/admin/subscription_helper.rb
module Admin::SubscriptionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orientations_helper.rb
module OrientationsHelper
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/views/admin/orientations/_form.html.haml
.container
  = simple_form_for [:admin, @orientation] do |f|
    = f.input :title
    = f.input :description
    = f.submit "Enviar"
    ou #{link_to "Cancelar", admin_orientations_path}

app/views/admin/orientations/edit.html.haml
%h2 Editar Orientação
= render :partial => "form"

app/views/admin/orientations/index.html.haml
%h2 Orientações - #{@orientations.count} registro(s)

#action-new= link_to "Nova orientação", new_admin_orientation_path, :class => "button"

- unless @orientations.blank?
  %table
    %thead
      %tr
        %th.first #{t("activerecord.attributes.orientation.title")}
        - if current_admin.superuser == true
          %th #{t("activerecord.attributes.orientation.admin.name")}
        %th #{t("activerecord.attributes.orientation.created_at")}
        %th.last
    %tbody
      - @orientations.each do |orientation|
        %tr{ :class => cycle("odd", "even") }
          %td= orientation.title
          - if current_admin.superuser == true
            %td= orientation.admin.name
          %td= l orientation.created_at, :format => :short
          %td.actions
            = link_to "Exibir", admin_orientation_path(orientation), :title => "Exibir #{orientation.title}"
            = link_to "Editar", edit_admin_orientation_path(orientation), :title => "Editar #{orientation.title}"
            = link_to "Excluir", [:admin, orientation], :confirm => "Tem certeza?", :method => :delete, :title => "Excluir #{orientation.title}"

app/views/admin/orientations/new.html.haml
%h2 Cadastrar Orientação
= render :partial => "form"

app/views/admin/orientations/show.html.haml
%h2 Exibir Orientação

.container
  - if current_admin.superuser?
    %p
      %strong #{t("activerecord.attributes.orientation.admin.name")}:
      = @orientation.admin.name
  %p
    %strong #{t("activerecord.attributes.orientation.title")}:
    = @orientation.title
  %p
    %strong #{t("activerecord.attributes.orientation.description")}:
    = @orientation.title

  #{link_to "Voltar", admin_orientations_path}

app/views/admin/users/_subscription.html.haml
%table
  %thead
    %tr
      %th{ :colspan => "4" } Dados Pessoais
  %body
    -if @user.personal_data.blank?
      %tr{ :class => cycle("odd", "even") }
        %td{:colspan => 4} dados pessoais não preenchidos
    -else
      %tr{ :class => cycle("odd", "even") }
        %td 
          %strong #{t("activerecord.attributes.personal_data.name")}: 
          %br
          #{@user.personal_data.name rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.gender")}: 
          %br
          #{@user.personal_data.gender rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.naturally")}: 
          %br
          #{@user.personal_data.naturally rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.nationality")}: 
          %br
          #{@user.personal_data.nationality rescue nil}
      %tr{ :class => cycle("odd", "even") }
        %td 
          %strong #{t("activerecord.attributes.personal_data.dob")}: 
          %br
          #{l @user.personal_data.dob rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.marital")}: 
          %br
          #{@user.personal_data.marital rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.rg")}: 
          %br
          #{@user.personal_data.rg rescue nil}
        %td &nbsp;
      %tr{ :class => cycle("odd", "even") }
        %td 
          %strong #{t("activerecord.attributes.personal_data.address")}: 
          %br
          #{@user.personal_data.address rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.district")}: 
          %br
          #{@user.personal_data.district rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.city")}: 
          %br
          -if @user.personal_data.city == "[Outros]"
            #{@user.personal_data.city rescue nil}
            #{@user.personal_data.other_city rescue nil}
          -else
            #{@user.personal_data.city rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.state")}: 
          %br
          #{@user.personal_data.state rescue nil}
      %tr{ :class => cycle("odd", "even") }
        %td 
          %strong #{t("activerecord.attributes.personal_data.zip_code")}: 
          %br
          #{@user.personal_data.zip_code rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.country")}: 
          %br
          #{@user.personal_data.country rescue nil}
        %td &nbsp;
        %td &nbsp;
      %tr{ :class => cycle("odd", "even") }
        %td 
          %strong #{t("activerecord.attributes.personal_data.home_phone")}: 
          %br
          #{@user.personal_data.home_phone rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.phone_message")}: 
          %br
          #{@user.personal_data.phone_message rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.business_phone")}: 
          %br
          #{@user.personal_data.business_phone rescue nil}
        %td 
          %strong #{t("activerecord.attributes.personal_data.cell_phone")}: 
          %br
          #{@user.personal_data.cell_phone rescue nil}

app/views/admin/users/index.html.haml
%h2 Usuários cadastrados pelo trabalhe conosco - #{@search.count} cadastros

= simple_form_for [:admin, @search], :url => {:action => :index}, :html => {:method => :get, :class => "container"} do |f|
  = f.input :personal_data_name_contains, :required => false, :label => "Nome"
  = f.input :email_contains, :required => false, :label => "E-mail"
  = f.input :personal_data_city_equals, :required => false, :label => "Cidade", :as => :select, :collection => PersonalData::CITIES
  = f.input :education_id_equals, :as => :select, :label => "Escolaridade", :collection => Education.options_to_filter, :required => false
  = f.input :complementary_physically_handicapped_equals, :as => :select, :collection => [["Sim", true], ["Não", false]], :label => "Deficiente físico?", :required => false
  = f.button :submit, "Buscar"

-if @users.blank?
  %p Nenhum usuário cadastrado.
- else @users.blank?
  %table
    %thead
      %tr
        %th.first CPF
        %th Nome
        %th Idade
        %th Cidade
        %th Cadastro
        %th.last
    %body
      - @users.each do |user|
        %tr{ :class => cycle("odd", "even") }
          %td= user.cpf
          %td= user.personal_data.name rescue nil
          %td= user.personal_data.dob_humanize rescue nil
          %td= user.personal_data.city rescue nil
          %td= l user.created_at, :format => :short
          %td.actions
            =link_to "Ver", admin_user_path(user)

  = will_paginate @users

app/views/admin/users/show.html.haml
%h2 Detalhes do cadastro #{@user.id} - #{@user.personal_data.name rescue nil}

.container
  %p
    Criado em #{l @user.created_at}
  %table
    %thead
      %tr
        %th{ :colspan => "3" } Dados de Acesso:
    %body
      %tr{ :class => cycle("odd", "even") }
        %td #{t("activerecord.attributes.user.cpf")}: #{@user.cpf}
        %td #{t("activerecord.attributes.user.email")}: #{@user.email}

  = render :partial => "personal_data"
  = render :partial => "education"
  = render :partial => "work_history"
  = render :partial => "complementary"

app/views/home/index.html.haml
.section
  %h3 BICICLETADA NACIONAL Rio+20
  %br.clearfix
  %p
    A BICICLETADA NACIONAL Rio+20 é uma grande mobilização de ciclistas de todas as partes do Brasil que formarão bondes e pedalarão até o Rio de Janeiro para fazer parte da RIO+20 e promover a divulgação deste meio de transporte diretamente ligado ao tema.
  %p
    A RIO+20 é a Conferência das Nações Unidas sobre Desenvolvimento Sustentável, que irá ocorrer no Brasil de 20 a 22 de junho de 2012 marcando o 20º aniversário da ECO92 e o 10º aniversário da WSSD. Com a presença de Chefes de Estado e de Governo ou outros representantes a expectativa é de uma Conferência do mais alto nível, sendo que dela resultará a produção de um documento político focado nas diretrizes do desenvolvimento mundial a ser seguido daqui em diante.
  %p
    O objetivo da Conferência e da Bicicletada Nacional é assegurar um comprometimento político renovado para o desenvolvimento sustentável em escala planetária , avaliar os progressos e as lacunas deixadas desde as últimas conferências, e abordar os novos desafios emergentes.
  %p
    A Bicicletada Nacional Rio+20 apresenta-se como forma de proporcionar uma imensa visibilidade ao tema: o uso da bicicleta está intimamente relacionado com todo um urgente e necessário planejamento e funcionamento das grandes cidades, e a bicicleta tem cada vez mais se mostrado uma excelente solução para os problemas enfrentados, especialmente aliada e integrada a outos modais de transporte eficientes. Espera-se, dessa forma, pressionar autoridades do mundo inteiro a abordarem essa questão de forma séria e contundente.
  %p
    Para saber como participar, apoiar e/ou se informar sobre a jornada, acesse e explore o conteúdo deste site.
  %p
    %strong Boa pedalada para todos, por um futuro mais agradável de imaginar!

  =link_to "Saiba mais", "bicicletada_nacional_rio_20"
  %br.clearfix

app/views/orientations/index.html.haml
- @orientations.each do |orientation|
  %div{ :id => orientation.title.parameterize("_") }
    %h1.sub= link_to orientation.title, :anchor => orientation.title.parameterize("_")
    %h5= "por #{orientation.admin.name} em #{l orientation.created_at}"
    %p.sub= orientation.description
  %br

app/views/users/new.html.haml
.section
  %h3 Inscrições
  %br.clearfix

  %p
    Para participar da Bicicletada Nacional Rumo à RIO+20 é necessário se inscrever utilizando o formulário abaixo. A inscrição é livre de custos e servirá apenas para controle logístico dos participantes.
    %strong Leia o termo de compromisso atentamente,
    pois ao se inscrever você estará de acordo com ele. Solicitamos que haja comprometimento no ato da inscrição, só efetuando a mesma se tiver certeza da participação.

  %p
    Os que se disporem bravamente a percorrer as rotas mais longas poderão ficar na estrada por mais de 20 dias. Por isso disponibilizamos um modelo de pedido de licença (link), a ser livremente reproduzido e adaptado conforme convir.

  %p
    %strong Ao participar da Bicicletada Nacional Rumo à RIO+20, o ciclista assume que está o fazendo por livre e espontânea vontade e assumindo todos os riscos, ficando responsável por sua própria integridade física e guarda de seus objetos e pertences.

  %p
    %strong Apesar de serem tomadas providências para minimizar os riscos, acidentes podem acontecer e cabe a cada um a decisão de continuar ou não de acordo com suas limitações.
  
  %p
    %strong O atendimento médico será providenciado, mas a cobertura de gastos não, ficando cada participante responsável pelo seu próprio seguro médico ou pagamento.

  %br
  %br

  = link_to "English", params.merge(:locale => "en"), :class => "list-links"
  = link_to "Português", params.merge(:locale => "pt-BR"), :class => "list-links"

  %br

  - flash.each do |name, message|
    = content_tag :div, message, :class => "message #{name}"
 
  = simple_form_for @user, :html => {:novalidate => true, :id => "subscription"} do |f|
    %h3 Formulário para Inscrição
    %br.clearfix
    = f.input :email, :input_html => {:class => "required"}
    = f.input :password, :input_html => {:class => "required"}
    = f.input :password_confirmation, :input_html => {:class => "required"}

    = f.fields_for :subscription do |p|
      = p.input :name, :input_html => {:class => "required"}
      - if params[:locale] == ""
        = p.input :passport, :input_html => {:class => "required"}
      = p.input :birth_day, :start_year => 1940, :include_blank => true, :input_html => {:class => "required", :alt => "date"}, :as => :string
      = p.input :birth_place, :input_html => {:class => "required"}
      = p.input :address, :input_html => {:class => "required"}
      = p.input :district, :input_html => {:class => "required"}
      = p.input :city, :input_html => {:class => "required"}
      = p.input :state, :input_html => {:class => "required"}
      = p.input :contact_phone, :input_html => {:class => "required", :alt => "phone"}, :as => :string
      = p.input :blood_type, :input_html => {:class => "required"}
      = p.input :allergy, :input_html => {:class => "required"}
      %h4 Em caso de emergência, avisar:
      %br.clearfix
      = p.input :emergency_name, :input_html => {:class => "required"}
      = p.input :emergency_address, :input_html => {:class => "required"}
      = p.input :emergency_contact_phone, :input_html => {:class => "required", :alt => "phone"}, :as => :string

      %h4 Termo de Compromisso
      %br.clearfix
      .terms
        %p
          O participante que tiver qualquer restrição em relação a saúde (alergias, epilepsia, asma, diabetes, etc...) deve informar na inscrição e trazer consigo seus medicamentos, com descrição de dosagem a ser aplicada caso ocorra qualquer anormalidade no seu estado de saúde durante o passeio.
        %p
          O participante que tiver qualquer restrição alimentar (vegetarianos, vegans, celíacos, intolerância à lactose, alergias a alimentos) deve informar na inscrição.
        %p
          O participante deve obrigatoriamente conhecer o Código de Trânsito Brasileiro - CTB - e suas regras. É exigido o comprometimento a respeitá-lo durante todo o percurso, seguindo todas as orientações dos agentes legais.
        %p
          %strong A organização recomenda fazer o uso de capacete durante todo o percurso. Apesar de um item não obrigatório pelo CTB, torna-se quase indispensável para a tranquilidade na estrada. Além de ser um bom chapéu.
        %p
          Recomenda-se também o uso de luvas e óculos conforme convir, bem como o uso de bermudas específicas para o ciclismo e demais vestimentas e equipamentos adequados à variação climática a ser enfrentada. Em nosso blog temos uma boa troca de experiência de ciclistas de todo país quanto a equipamentos e dicas gerais de cicloviagens, confira.

      = p.input :accept, :label => "Li o termo de compromisso e concordo com todos os itens descritos no mesmo"

    = f.submit "Enviar"

    %br.clearfix