config/routes.rb
Bicicletada::Application.routes.draw do

  # login
  devise_for :admins

  # /admin
  namespace :admin do
    root :to => 'dashboard#index'
    resources :subscriptions, :only => [:index, :show]
    resources :admins
    resources :orientations
  end

  scope "(:locale)", :locale => /pt-BR|en/ do
    root :to => 'home#index'
    resources :users
    resource :bicicletada_nacional_rio_20, :as => :about, :controller => :about, :only => [:show]
    resource :rotas_bicicletada_nacional, :as => :routes, :controller => :routes, :only => [:show]
    resource :organizadores, :as => :organizers, :controller => :organizers, :only => [:show]
    resource :apoio, :as => :support, :controller => :support, :only => [:show]
    resource :contato, :as => :contact, :controller => :contact, :only => [:show]
    resources :orientacoes, :as => :orientations, :controller => :orientations, :only => [:index]
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base

  validates :name, :state, :presence => true
  validates :superuser, :inclusion => [true, false]

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :registerable
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :state, :superuser

  has_many :orientations
end

app/models/orientation.rb
class Orientation < ActiveRecord::Base
  belongs_to :admin
end

app/models/subscription.rb
#encoding: utf-8
class Subscription < ActiveRecord::Base

  validates :accept, :inclusion => { :in => [true], :message => "blabla" } 

  attr_accessible :name, :birth_day, :birth_place, :address, :district, :city,
                  :state, :contact_phone, :blood_type, :allergy, :emergency_name,
                  :emergency_address, :emergency_contact_phone, :rio20, :cupula_dos_povos,
                  :accept

  def rio20_humanize
    rio20? ? "Sim" : "Não"
  end

  def cupula_dos_povos_humanize
    cupula_dos_povos? ? "Sim" : "Não"
  end

  #Relationships
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :subscription_attributes

  #Validations
  validates :email, :presence => true, :uniqueness => true

  #Relationships
  has_one :subscription
  accepts_nested_attributes_for :subscription, :allow_destroy => true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/admin/admins_controller.rb
# encoding: utf-8

class Admin::AdminsController < ApplicationController

  layout 'admin'

  before_filter :admin_superuser
  before_filter :authenticate_admin!
  before_filter :admin, :only => [:edit, :update, :destroy]

  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params[:admin])

    if @admin.save
      redirect_to(admin_admins_url, :notice => 'Usuário cadastrado com sucesso!')
    else
      render :action => "new"
    end
  end

  def edit
  end

  def update
    if @admin.update_attributes(params[:admin])
      redirect_to(admin_admins_url, :notice => 'Usuário atualizado com sucesso!')
    else
      render :action => "edit"
    end
  end

  def destroy
    @admin.destroy
    redirect_to(admin_admins_url, :notice => 'Usuário excluído com sucesso!')
  end

  private

  def admin
    @admin = Admin.find(params[:id])
  end

  def admin_superuser
    if !current_admin.superuser? && (params[:id] != current_admin.id.to_s)
      redirect_to(admin_root_path, :notice => "Você não tem permissão para acessar esta página.")
    end
  end
end

app/controllers/admin/dashboard_controller.rb
# encoding: utf-8

class Admin::DashboardController < ApplicationController

  layout 'admin'

  before_filter :authenticate_admin!

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :set_locale
  layout :layout_by_resource

  protect_from_forgery

  def subscriptions_counting
    @subscriptions_counting = Subscription.count
    @orientations = Orientation.joins(:admin).where("admins.superuser = 1").order("orientations.created_at DESC")
  end

  private

  def set_locale
    I18n.locale = params[:locale] if params.include?('locale')
  end

  def default_url_options(options={})
    options.merge!({ :locale => I18n.locale })
  end

  protected

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "admin"
    else
      "application"
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/orientations_controller.rb
class OrientationsController < ApplicationController 
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
  before_filter :subscriptions_counting

  def index
  end
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
  before_filter :subscriptions_counting

  def new
    @user = User.new
    @user.build_subscription if @user.subscription.blank?
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to(root_path, :notice => "Ficha de inscrição cadastrada com sucesso!")
    else
      flash[:error] = "NÃO FOI POSSÍVEL COMPLETAR SEU CADASTRO, FAVOR VERIFICAR SE OS DADOS ESTÃO PREENCHIDOS CORRETAMENTE."
      render :action => "new"
    end
  end

end

app/helpers/admin/subscription_helper.rb
module Admin::SubscriptionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orientations_helper.rb
module OrientationsHelper
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/views/admin/admins/_form.html.haml
.container
  = simple_form_for [:admin, @admin], :html => { :novalidate => true } do |f|
    = f.input :name
    = f.input :state, :as => :select, :collection => ["AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"]
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
    - if @admin.superuser?
      = f.input :superuser
    = f.button :submit, "Enviar"
    ou #{link_to "Cancelar", admin_admins_path}

app/views/admin/admins/edit.html.haml
%h2 Editar Usuário
= render :partial => "form"

app/views/admin/admins/index.html.haml
%h2 Usuários - #{@admins.count} registro(s)

#action-new= link_to "Novo Usuário", new_admin_admin_path, :class => "button"

- unless @admins.blank?
  %table
    %thead
      %tr
        %th.first #{t("activerecord.attributes.admin.name")}
        %th #{t("activerecord.attributes.admin.email")}
        %th #{t("activerecord.attributes.admin.state")}
        %th #{t("activerecord.attributes.admin.superuser")}
        %th.last
    %body
      - @admins.each do |admin|
        %tr{ :class => cycle("odd", "even") }
          %td= admin.name
          %td= admin.email
          %td= admin.state
          %td= admin.superuser
          %td.actions
            = link_to "Editar", edit_admin_admin_path(admin), :title => "Editar #{admin.email}" unless current_admin == admin
            = link_to "Excluir", [:admin, admin], :confirm => "Tem certeza?", :method => :delete, :title => "Excluir #{admin.email}" unless current_admin == admin

app/views/admin/admins/new.html.haml
%h2 Cadastrar Usuário
= render :partial => "form"